### PR TITLE
Switch redrawVueMasonry() to instance method

### PR DESCRIPTION
**Pull request by mikerogerz**
To be used correctly within components.

Example:
`this.$nextTick(function () {
	this.$redrawVueMasonry()
})`

### CODE REVIEW

**Comment by shershen08** [comment]
Thanks for a clever input @mikerogerz 
I am now making sure that the major problem raised in #26 is fixed. As son as it's stable I'll add your PR

**Comment by mikeevstropov** [comment]
Calling from component
```console
TypeError: this.redrawVueMasonry is not a function
```
```console
TypeError: this.$redrawVueMasonry is not a function
```

**Comment by mikerogerz** [comment]
@mikeevstropov I just synced my patch with upstream and updated the dist js (where it's being loaded from.. not src, where I made the initial change). Try again with my fork and it should work fine.

@shershen08 If you don't see any issues, it would be great to see this merged.

**Comment by mikeevstropov** [comment]
@mikerogerz I did this 20 minutes ago. Thank you!

**Comment by shershen08** [comment]
Thanks for you participation @mikerogerz @mikeevstropov 
Merged the PR in https://github.com/shershen08/vue-masonry/commit/be75b5a8d9b6b9dd3675f83865ed5cba6794448e

**Pull request merged**
