### PR TITLE
Use masonry from npm package

### PR DESCRIPTION
**Pull request by jonatanl**
Thought it would be nice to use masonry from npm package instead of using cdn. What do you think?

Great library by the way!

### CODE REVIEW

**Comment by shershen08** [comment]
Yes I was struggling how to arrange it better by default.

**Comment by shershen08** [comment]
Did you test it works OK?

**Comment by jonatanl** [comment]
Worked just fine when I tested it :)

**Comment by shershen08** [comment]
Worked for me as well, merging

**Pull request merged**
