### PR TITLE
Fix: Accept ID as value to allow multiple instances

### LINKED ISSUE #59: Multiple instances issue
I have two (vuetify) tabs, each of which has a masonry element. If I add an item to the active tab and then switch tabs, all elements of the newly selected tab are stacked on top of each other.

I'm calling redrawVueMasonry ~~on the add~~, when a tab switch happens, but it doesn't seem to fix the problem... Any ideas?

edit: I appreciate your work on this package btw!

### PR DESCRIPTION
**Pull request by benjamindedonder**
This fixes #59 

new usage:
```
<div v-masonry="masonryId" transition-duration="0.3s" item-selector=".item">
  <div v-masonry-tile="masonryId" class="item" v-for="(item, index) in blocks">
    <!-- block item markup -->
  </div>
</div>
```
```
export default {
  data: () => ({
    masonryId: 'masonry-grid-1'
  })
}
```
```
this.$redrawVueMasonry('masonry-grid-1')
```

### CODE REVIEW

**Comment by shershen08** [comment]
Thanks for the input, I'll check that soon

**Comment by benjamindedonder** [comment]
No problem, thank you for bringing Masonry to Vue. :)

This fix is also possible using an attribute instead of taking the value from bindings. Depends on what you prefer.

**Comment by benjamindedonder** [comment]
If you need any help maintaining this project, I would love to do so.

**Comment by shershen08** [comment]
Thanks for your contribution @benjamindedonder

**Comment by kirkbushell** [comment]
Are we sure this works? I've defined the ID and tried to get it to work numerous times, all to no avail.

**Comment by kirkbushell** [comment]
In fact every time I define an ID, the library bugs out.

**Comment by benjamindedonder** [comment]
I mean to remember this was working for me. I have no idea about how you are using it of course, so I can't really help you out.

But I ended up simply using the [Masonry library](https://masonry.desandro.com) directly in my application which worked best for me. After all, this plugin simply wraps this library into a Vue Directive.

**Comment by schnider94** [comment]
I had the same problem as @kirkbushell but after I looked into the code I saw that the id needs to be set on the v-masonry and the v-masonry-tile (so that events get send correctly). After adding it to both, everything worked as expected for me.

I think it would be good to add that to the README, right now it doesn't say it anywhere.

**Pull request merged**
