### PR TITLE
Updated Readme to cater for nuxt ssr

### PR DESCRIPTION
**Pull request by richlloydmiles**

### CODE REVIEW

**Comment by shershen08** [comment]
@richlloydmiles great input! I've checked the input and this looks OK to me.
Would that be a problem to create a simple demo repo with SSR + vue-masonry to demo this case ? 
For 2 purposes: 
 - separate reference implementation of what's in the README
 - independent test project for further plugin upgrades

Like I have for basic vue-masonry - https://github.com/shershen08/vue-masonry-plugin-demo

**Comment by richlloydmiles** [comment]
@shershen08 yes I can definitely do that.

**Comment by richlloydmiles** [comment]
@shershen08  I have added an example repo link to the readme with working code - https://github.com/richlloydmiles/example-vue-masonry-ssr

**Comment by shershen08** [comment]
Great job @richlloydmiles 
I'll take a look and proceed today

**Pull request merged**
