### PR TITLE
Vue 3 Support added

### PR DESCRIPTION
**Pull request by cintax**
### Vue-Masonry for Vue 3
  - Created a new ```masonry-vue3.plugin.js``` plugin file for Vue 3 implementation
  - Dependency:
    - [mitt](https://www.npmjs.com/package/mitt) package
  - In your Vue 3 app, you'll have the following code

    ```
    import { createApp } from 'vue'
    import mitt from 'mitt'

    import { VueMasonryPlugin } from "vue-masonry/src/masonry-vue3.plugin";

    const emitter = mitt()
    let app = createApp(App)
    app.config.globalProperties.emitter = emitter
    app.use(VueMasonryPlugin)
    app.mount('#app')

    <div v-masonry="containerId" transition-duration="0.3s" item-selector=".item">
      <div v-masonry-tile class="item" v-for="(item, index) in blocks">
        <!-- block item markup -->
      </div>
    </div>
    ```

### CODE REVIEW

**Comment by shershen08** [comment]
Thanks for the PR @cintax 
is that absolute need to and an extra package in v3 version?
```
import mitt from 'mitt'
```

**Comment by cintax** [comment]
@shershen08 pleasure!

As mentioned in the official Vue 3 [documentation](https://v3.vuejs.org/guide/migration/events-api.html#migration-strategy),
It is no longer possible to use Events APIs to listen to a component's own emitted events from within a component, there is no migration path for that use case.

One alternative can be implementing something like [this](https://stackoverflow.com/questions/63471824/vue-js-3-event-bus#answer-64045893) but '**mitt**' does the same thing.

**Comment by CKGrafico** [comment]
For those that are waiting this PR you can use like `"vue-masonry": "cintax/vue-masonry#vue-3-support",` please @cintax  don't delete your branch xD

**Comment by DhvanilPatel** [comment]
Hi @shershen08 – would it be possible to merge this PR so we can directly use `npm i vue-masonry` for vue-3 projects?

**Comment by CKGrafico** [comment]
applause thanks

Thanks

**Comment by DhvanilPatel** [comment]
Thank you 🎉💫

**Comment by shershen08** [comment]
Thanks everyone for patience 😌

**Pull request merged**
